//
// Created by garwi on 11/27/2020.
//

#ifndef MUSIC_VISUALIZER_SRC_MUSIC_PLAYER_MUSIC_PLAYER_H_
#define MUSIC_VISUALIZER_SRC_MUSIC_PLAYER_MUSIC_PLAYER_H_

#endif //MUSIC_VISUALIZER_SRC_MUSIC_PLAYER_MUSIC_PLAYER_H_
